### ISSUE TITLE
python-docker-dev-server crashes on launching the database KeyError: 'POSTGRES_PASSWORD'

### ISSUE THREAD

**Issue by MrDarkness117** [docker/python-docker-dev#7]
After launching docker-compose the db crashes.
My compose.yaml
```
# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    build:
      context: .
    ports:
      - 5000:5000

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_DB_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_PASSWORD=admin
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
```

The logs:
```
python-docker-dev-db-1      | 2023-11-28 21:20:10.941 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
python-docker-dev-db-1      | 2023-11-28 21:20:10.941 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
python-docker-dev-db-1      | 2023-11-28 21:20:10.941 UTC [1] LOG:  listening on IPv6 address "::", port 5432
python-docker-dev-db-1      | 2023-11-28 21:20:10.962 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
python-docker-dev-db-1      | 2023-11-28 21:20:10.982 UTC [17] LOG:  database system was shut down at 2023-11-28 21:18:56 UTC
python-docker-dev-db-1      | 2023-11-28 21:20:10.999 UTC [1] LOG:  database system is ready to accept connections
python-docker-dev-server-1  | Traceback (most recent call last):
python-docker-dev-server-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
python-docker-dev-server-1  |   File "<frozen runpy>", line 88, in _run_code
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/flask/__main__.py", line 3, in <module>
python-docker-dev-server-1  |     main()
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 1063, in main
python-docker-dev-server-1  |     cli.main()
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
python-docker-dev-server-1  |     rv = self.invoke(ctx)
python-docker-dev-server-1  |          ^^^^^^^^^^^^^^^^
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
python-docker-dev-server-1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
python-docker-dev-server-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
python-docker-dev-server-1  |     return ctx.invoke(self.callback, **ctx.params)
python-docker-dev-server-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
python-docker-dev-server-1  |     return __callback(*args, **kwargs)
python-docker-dev-server-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 92, in new_func
python-docker-dev-server-1  |     return ctx.invoke(f, obj, *args, **kwargs)
python-docker-dev-server-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
python-docker-dev-server-1  |     return __callback(*args, **kwargs)
python-docker-dev-server-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 911, in run_command
python-docker-dev-server-1  |     raise e from None
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 897, in run_command
python-docker-dev-server-1  |     app = info.load_app()
python-docker-dev-server-1  |           ^^^^^^^^^^^^^^^
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 312, in load_app
python-docker-dev-server-1  |     app = locate_app(import_name, None, raise_if_not_found=False)
python-docker-dev-server-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python-docker-dev-server-1  |   File "/usr/local/lib/python3.11/site-packages/flask/cli.py", line 218, in locate_app
python-docker-dev-server-1  |     __import__(module_name)
python-docker-dev-server-1  |   File "/app/app.py", line 7, in <module>
python-docker-dev-server-1  |     password = os.environ['POSTGRES_PASSWORD']
python-docker-dev-server-1  |                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
python-docker-dev-server-1  |   File "<frozen os>", line 679, in __getitem__
python-docker-dev-server-1  | KeyError: 'POSTGRES_PASSWORD'
python-docker-dev-server-1 exited with code 1
```
